### ISSUE TITLE
Treat org.freenas.* as reserved for things that are official to FreeNAS

### ISSUE THREAD

**Issue by grahamperrin** [fracai/zfs-rollup#3]
At https://gist.github.com/fracai/725e5c04dee5d2fb7fe8: 

> org.freenas.time-machine-snapshot.plist

– that implies something official from within the freenas.org domain. 

Instead, please use something that unambiguously identifies you (the author), or the project from which the code originates. 

----

An example, for something that I created for use with ZEVO: 

    sh-3.2$ defaults read /Library/LaunchDaemons/net.redirectme.perrin.zevo-ce-1-1-1-tuner.plist Label
    net.redirectme.perrin.zevo-ce-1-1-1-tuner
    sh-3.2$

**Comment by fracai** [comment]
Very valid. I personally use a different prefix on my own machine, but figured a more generic name would be more appropriate. I'll change it to fracai.zfs-rollup and include a note that it can be changed as desired.
