### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by rueckix** [fracai/zfs-rollup#7]
Using this on FreeNAS 11.3 requires a migration to Python 3. 

For those having similar problems, here's a quick fix.

1. a simply 2to3 conversion takes care of most of the issue
2. an additional insert of `decode()` is required in the rollup.py.
`name,property,value = snapshot.decode().split('\t',3)`

This is not a proper fix as python3 may need further work.

**Comment by fracai** [comment]
Yeah, I switched the #! to specify python2, but that's a hack that should be fixed.
Does 11.3 not include python2 anymore? I'll take a look at this soon.

**Comment by fracai** [comment]
I think I've updated all the necessary python3 changes. Let me know if there are any issues

**Comment by rueckix** [comment]
For me 11.3 does not have python2 any longer. I will run a test with the changes

**Comment by rueckix** [comment]
rollup.py is behaving as expected (args `--test -p audo -r <dataset>`)
clearempty is behaving as expected (args `--test -r <dataset`)

Cannot say much about tmsnap.py and snap-strip.py. I never used them before.

**Comment by fracai** [comment]
Thanks for the report.
I don't use tmsnap anymore either, but snap-strip is working for me.
